### ISSUE TITLE
Game not opening at all.

### ISSUE THREAD

**Issue by Wave720** [ibldzn/yakuza-0-legend-style-fix#5] opened 2021-04-13 00:22 UTC
- [x] I have read the whole [README](https://github.com/ibldzn/yakuza-0-legend-style-fix#readme) especially the [I'm having issue with your mod, what should I do?](https://github.com/ibldzn/yakuza-0-legend-style-fix#im-having-issue-with-your-mod-what-should-i-do) segment and have tried the solution given there.
- [x] I am using the latest Steam version of the game.

_Place an "x" without quotation mark inside the bracket to check the checkbox, so it'll look like this:_ [x] (no space between x and brackets).

---

<h3>
  <p align="center">
    <b>
        Please note that your issue will be immediately closed if there's unchecked checkbox.
    </b>
  </p>
</h3>

---

**Describe The Issue** 
I followed your installation instructions and now when I try to open my game nothing happens at all, no "Steam is launching your game" or anything, just refuses to open.

**Screenshots**
If there's an error message, attach the screenshots below.
There's no error message or anything really, it'd look the same if you did nothing while looking at the launch button instead of pressing it.

**Desktop (please complete the following information):**

- OS: Windows 10
- Mod Version: 0.9b

**Additional context**
I have no other mods installed, this was the first one.
The game worked fine again when I deleted the file I had put in the Yakuza folder.

**Comment by ibldzn** [comment] 2021-04-13 00:27
does it really not work with ASI Loader? 
the mod won't mess with DirectX API function in the .asi version thus issue like this should not happen with the .asi version.

**Comment by Wave720** [comment] 2021-04-13 00:37
Unless I somehow messed up the process along the way, it didn't work

**Comment by ibldzn** [comment] 2021-04-13 00:44
strange.. I'm using Windows 10 with the Steam version of the game and have never had any issue for months.

have you tried the DLL injection method?
if you have and it's still not working can you tell me what asi loader you're using?

**Comment by Wave720** [comment] 2021-04-13 01:00
Yeah, I tried the one in your read me the first time and it didn't work, just tried again and still nothing.

**Comment by ibldzn** [comment] 2021-04-13 01:06
you're using this version, right?
![Screenshot](https://i.imgur.com/2yHu8nP.png)

**Comment by Wave720** [comment] 2021-04-13 01:27
Yeah, I was but I decided to redownload everything and now I'm getting an error message. 

![image](https://user-images.githubusercontent.com/82422526/114483035-8f6a3480-9bff-11eb-8c6a-f20f9ddd4496.png)

The game launches afterwards but without the mod.

**Comment by ibldzn** [comment] 2021-04-13 01:32
![Screenshot](https://i.imgur.com/SbgpB2T.png)

show me a screenshot of your root Y0 directory.

**Comment by Wave720** [comment] 2021-04-13 01:38
Looks the same as the one above as far as I can tell unless I'm being dumb.

![image](https://user-images.githubusercontent.com/82422526/114483758-e15f8a00-9c00-11eb-8755-062ba544d9b5.png)

**Comment by ibldzn** [comment] 2021-04-13 01:52
no you're not, this is such a weird issue. 
![Screenshot](https://i.imgur.com/yPGtxDE.png)
here my .asi is automatically loaded upon game start, I'm sorry but I can't reproduce your error on my end.

**Comment by Wave720** [comment] 2021-04-13 02:10
Maybe it's something not in the folder screwing it up.

I have no knowledge of stuff like this at all but I thought I might as well list some stuff I'm thinking about.

Different region/country.

I bought the game in a steam bundle (off of steam) with Kiwami 1 & 2.

No idea if they would change anything but I can't think of anything else that could be different.

**Comment by ibldzn** [comment] 2021-04-13 02:59
I don't think they're distributing different executable for a game bought off of a bundle nor for different region, some region might have a different asset used but the game code should still be the same (at least that is the case for Yakuza 0, I've tried the Japanese depot version of the game).

also all of the "game address" needed for this mod to work is [obtained dynamically](https://github.com/ibldzn/yakuza-0-legend-style-fix/blob/51440ca0bc9a291427cf52e70579f3946538a0dc/yakuza-0-legend-style-fix/src/hooks/hooks.cpp#L20), nothing's hardcoded, if my code failed to obtain the "game address" there should be a popup message like [this one](https://github.com/ibldzn/yakuza-0-legend-style-fix/blob/51440ca0bc9a291427cf52e70579f3946538a0dc/yakuza-0-legend-style-fix/src/hooks/hooks.cpp#L22).

**Comment by Wave720** [comment] 2021-04-13 03:37
Then I got no clue, just seems odd for it to not work for seemingly no reason.

Also what happens now? I literally created an account on here to post this so I'm new to everything here.

Do I just leave this up or do I close it? Since You've got no idea what's going on there's not much else to add, right?

**Comment by ibldzn** [comment] 2021-04-13 04:12
it's up to you, I don't see any harm leaving your account as is, you can also delete it if you want.

I'm closing this issue.

**Closed by ibldzn** 2021-04-13 04:12 UTC
