### ISSUE TITLE
Please HELP

### ISSUE THREAD

**Issue by AhlamDL** [ibldzn/yakuza-0-legend-style-fix#21] opened 2023-03-11 08:19 UTC
![HELP](https://user-images.githubusercontent.com/127532764/224473445-07e767fa-d341-47b4-9968-8b6ea401be71.PNG)

How to fix this

**Comment by ibldzn** [comment] 2023-03-11 17:41
duplicate of #19

anyway, that is a forked version of my mod, I didn't make that, if you want to use a custom keybinding then you can already do that with my mod, kindly read the readme

**Closed as completed** 2023-03-11 17:41 UTC
